### PR TITLE
Set keyguard indication bottom margin to 14dp

### PR DESCRIPTION
**Pull request by ghost**
The recently changed 10dp indication margin bottom leads to partially visible text on ambient display while charging.

### CODE REVIEW

**Comment by idoybh** [comment]
We have more than 1 device. Which DPI do you use ?
Also the correct way to go about this git-wise is a revert, not an extra commit.

**Comment by idoybh** [comment]
Closing for now. Continue discussion here. If we decide for this change I will revert recent DT commits all across.

**Comment by idoybh** [comment]
Aight. Dropped the change from all relevant repos. Thanks for reporting @RedSkulHYDRA

**Comment by RealJohnGalt** [comment]
Commit dropped from hotdogb. My comment from internals below:

That HDB one I'm fine just dropping your original commit. 

It was because it was close to overlapping with udfps, not even overlapping. But with your commit it can get cutoff bottom with aod.

**Pull request closed without merging**
